name: Trigger auto deployment for gh2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app71 ]
    paths:
    - '**'
    - '.github/workflows/gh2-AutoDeployTrigger-23d54a32-83b0-4b80-9777-c67fe0d772e2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sstrawn.azurecr.io
          username: ${{ secrets.GH2_REGISTRY_USERNAME }}
          password: ${{ secrets.GH2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sstrawn.azurecr.io/gh2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GH2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gh2 -g container_apps --server sstrawn.azurecr.io --username  ${{ secrets.GH2_REGISTRY_USERNAME }} --password ${{ secrets.GH2_REGISTRY_PASSWORD }}
            az containerapp update -n gh2 -g container_apps --image sstrawn.azurecr.io/gh2:${{ github.sha }}
