name: Trigger auto deployment for containerapp upgh36

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app36 ]
    paths:
    - '**'
    - '.github/workflows/upgh36-AutoDeployTrigger-1bc7ad32-e800-4cc6-995f-a3a2c4aa062a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh364875290576acr.azurecr.io
          username: ${{ secrets.UPGH36_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH36_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh364875290576acr.azurecr.io/upgh36:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH36_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh36 -g sca --server caupgh364875290576acr.azurecr.io --username  ${{ secrets.UPGH36_REGISTRY_USERNAME }} --password ${{ secrets.UPGH36_REGISTRY_PASSWORD }}
            az containerapp update -n upgh36 -g sca --image caupgh364875290576acr.azurecr.io/upgh36:${{ github.sha }}
