name: Trigger auto deployment for containerapp upghmain

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/upghmain-AutoDeployTrigger-c1373f1a-5e2d-422a-8e1b-58ceb0049c45.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupghmain3467442204acr.azurecr.io
          username: ${{ secrets.UPGHMAIN_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGHMAIN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupghmain3467442204acr.azurecr.io/upghmain:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGHMAIN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upghmain -g sca --server caupghmain3467442204acr.azurecr.io --username  ${{ secrets.UPGHMAIN_REGISTRY_USERNAME }} --password ${{ secrets.UPGHMAIN_REGISTRY_PASSWORD }}
            az containerapp update -n upghmain -g sca --image caupghmain3467442204acr.azurecr.io/upghmain:${{ github.sha }}
