name: Trigger auto deployment for containerapp upgh31

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app31 ]
    paths:
    - '**'
    - '.github/workflows/upgh31-AutoDeployTrigger-8b62bcff-2b05-4e12-a5df-11d5b31b1dbd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh315357592462acr.azurecr.io
          username: ${{ secrets.UPGH31_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH31_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh315357592462acr.azurecr.io/upgh31:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH31_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh31 -g sca --server caupgh315357592462acr.azurecr.io --username  ${{ secrets.UPGH31_REGISTRY_USERNAME }} --password ${{ secrets.UPGH31_REGISTRY_PASSWORD }}
            az containerapp update -n upgh31 -g sca --image caupgh315357592462acr.azurecr.io/upgh31:${{ github.sha }}
