name: Trigger auto deployment for containerapp upgh20

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app20 ]
    paths:
    - '**'
    - '.github/workflows/upgh20-AutoDeployTrigger-6efceb62-43af-4113-b4d1-42348687cc3c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: upgh20acr4975204405269723912.azurecr.io
          username: ${{ secrets.UPGH20_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH20_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upgh20acr4975204405269723912.azurecr.io/upgh20:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH20_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh20 -g sca --server upgh20acr4975204405269723912.azurecr.io --username  ${{ secrets.UPGH20_REGISTRY_USERNAME }} --password ${{ secrets.UPGH20_REGISTRY_PASSWORD }}
            az containerapp update -n upgh20 -g sca --image upgh20acr4975204405269723912.azurecr.io/upgh20:${{ github.sha }}
