name: Trigger auto deployment for containerapp upgh29

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app29 ]
    paths:
    - '**'
    - '.github/workflows/upgh29-AutoDeployTrigger-6ac09e1a-aeca-439f-9706-c401a0d7764b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: upgh29acr1924235657.azurecr.io
          username: ${{ secrets.UPGH29_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH29_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upgh29acr1924235657.azurecr.io/upgh29:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH29_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh29 -g container_apps --server upgh29acr1924235657.azurecr.io --username  ${{ secrets.UPGH29_REGISTRY_USERNAME }} --password ${{ secrets.UPGH29_REGISTRY_PASSWORD }}
            az containerapp update -n upgh29 -g container_apps --image upgh29acr1924235657.azurecr.io/upgh29:${{ github.sha }}
