name: Trigger auto deployment for containerapp upgh32

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app32 ]
    paths:
    - '**'
    - '.github/workflows/upgh32-AutoDeployTrigger-a2f47455-d0f9-4497-9d66-586cce79ac31.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caeuap1342174440acr.azurecr.io
          username: ${{ secrets.UPGH32_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH32_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caeuap1342174440acr.azurecr.io/upgh32:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH32_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh32 -g sca --server caeuap1342174440acr.azurecr.io --username  ${{ secrets.UPGH32_REGISTRY_USERNAME }} --password ${{ secrets.UPGH32_REGISTRY_PASSWORD }}
            az containerapp update -n upgh32 -g sca --image caeuap1342174440acr.azurecr.io/upgh32:${{ github.sha }}
