name: Trigger auto deployment for containerapp upgh37

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app37 ]
    paths:
    - '**'
    - '.github/workflows/upgh37-AutoDeployTrigger-cb8a2604-a4ac-4bb2-b733-86ee03d8d668.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh372971129820acr.azurecr.io
          username: ${{ secrets.UPGH37_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH37_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh372971129820acr.azurecr.io/upgh37:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH37_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh37 -g sca --server caupgh372971129820acr.azurecr.io --username  ${{ secrets.UPGH37_REGISTRY_USERNAME }} --password ${{ secrets.UPGH37_REGISTRY_PASSWORD }}
            az containerapp update -n upgh37 -g sca --image caupgh372971129820acr.azurecr.io/upgh37:${{ github.sha }}
