name: Trigger auto deployment for containerapp upgh39

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app39 ]
    paths:
    - '**'
    - '.github/workflows/upgh39-AutoDeployTrigger-0e39c5a0-f21f-4d71-be98-99baf54ab430.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh398118836442acr.azurecr.io
          username: ${{ secrets.UPGH39_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH39_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh398118836442acr.azurecr.io/upgh39:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH39_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh39 -g sca --server caupgh398118836442acr.azurecr.io --username  ${{ secrets.UPGH39_REGISTRY_USERNAME }} --password ${{ secrets.UPGH39_REGISTRY_PASSWORD }}
            az containerapp update -n upgh39 -g sca --image caupgh398118836442acr.azurecr.io/upgh39:${{ github.sha }}
