name: Trigger auto deployment for containerapp upgh38

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app38 ]
    paths:
    - '**'
    - '.github/workflows/upgh38-AutoDeployTrigger-2217a54a-5089-4b5e-8611-488d4705d8f5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh387235400165acr.azurecr.io
          username: ${{ secrets.UPGH38_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH38_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh387235400165acr.azurecr.io/upgh38:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH38_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh38 -g sca --server caupgh387235400165acr.azurecr.io --username  ${{ secrets.UPGH38_REGISTRY_USERNAME }} --password ${{ secrets.UPGH38_REGISTRY_PASSWORD }}
            az containerapp update -n upgh38 -g sca --image caupgh387235400165acr.azurecr.io/upgh38:${{ github.sha }}
