name: Trigger auto deployment for containerapp upgh40

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app40 ]
    paths:
    - '**'
    - '.github/workflows/upgh40-AutoDeployTrigger-2b5c679b-737e-4cd7-9f0b-8a316556c156.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: caupgh408149699176acr.azurecr.io
          username: ${{ secrets.UPGH40_REGISTRY_USERNAME }}
          password: ${{ secrets.UPGH40_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caupgh408149699176acr.azurecr.io/upgh40:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.UPGH40_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n upgh40 -g sca --server caupgh408149699176acr.azurecr.io --username  ${{ secrets.UPGH40_REGISTRY_USERNAME }} --password ${{ secrets.UPGH40_REGISTRY_PASSWORD }}
            az containerapp update -n upgh40 -g sca --image caupgh408149699176acr.azurecr.io/upgh40:${{ github.sha }}
